version: '3.8'

services:
  microservices-dashboard:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "healthcheck.js"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - microservices-net

  # Example microservices
  user-service:
    build:
      context: .
      dockerfile: Dockerfile.example
    command: ["node", "examples/user-service.js"]
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - microservices-net

  product-service:
    build:
      context: .
      dockerfile: Dockerfile.example
    command: ["node", "examples/product-service.js"]
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - microservices-net

  order-service:
    build:
      context: .
      dockerfile: Dockerfile.example
    command: ["node", "examples/order-service.js"]
    ports:
      - "3003:3003"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
